### ISSUE TITLE
Trouble Installing on Mac OS X

### ISSUE THREAD

**Issue by AJDBenner** [mozilla/webmaker-suite#44]
Hi, I'm currently trying to install webmaker-suite. When I try to install all the components I get this error:

```
npm WARN engine sqlite3@2.2.0: wanted: {"node":">= 0.8.0 < 0.11.0"} (current: {"node":"0.12.0","npm":"2.5.1"})

> bcrypt@0.8.0 install /Users/andrewbenner/Desktop/gitHub/webmaker-suite/login.webmaker.org/node_modules/bcrypt
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
gyp: /Users/andrewbenner/node/common.gypi not found (cwd: /Users/andrewbenner/Desktop/gitHub/webmaker-suite/login.webmaker.org/node_modules/bcrypt) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/andrewbenner/Desktop/gitHub/webmaker-suite/login.webmaker.org/node_modules/bcrypt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
```

**Comment by AJDBenner** [comment]
I tried changing sqlite version to 3.0.0 however I noticed that this happens for multiple things
```
> bcrypt@0.8.0 install /Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/bcrypt
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
gyp: /Users/andrewbenner/node/common.gypi not found (cwd: /Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/bcrypt) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/bcrypt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
|
> dtrace-provider@0.2.8 install /Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/messina/node_modules/bunyan/node_modules/dtrace-provider
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
gyp: /Users/andrewbenner/node/common.gypi not found (cwd: /Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/messina/node_modules/bunyan/node_modules/dtrace-provider) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/messina/node_modules/bunyan/node_modules/dtrace-provider
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing dtrace-provider@0.2.8

> node-expat@2.0.0 install /Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/webmaker-download-locales/node_modules/xml2json/node_modules/node-expat
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
gyp: /Users/andrewbenner/node/common.gypi not found (cwd: /Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/webmaker-download-locales/node_modules/xml2json/node_modules/node-expat) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/webmaker-download-locales/node_modules/xml2json/node_modules/node-expat
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

> sqlite3@3.0.0 install /Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Command failed: /usr/local/bin/node --eval require('/Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node')
dyld: lazy symbol binding failed: Symbol not found: __ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_NS_17PropertyAttributeE
  Referenced from: /Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_NS_17PropertyAttributeE
  Referenced from: /Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node
  Expected in: dynamic lookup


node-pre-gyp ERR! Testing pre-built binary failed, attempting to source compile
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
gyp: /Users/andrewbenner/node/common.gypi not found (cwd: /Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/sqlite3) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=sqlite3" "--configuration=Release" "--module_name=node_sqlite3" "--version=3.0.0" "--major=3" "--runtime=node" "--node_abi=node-v14" "--platform=darwin" "--target_platform=darwin" "--arch=x64" "--target_arch=x64" "--module_main=./lib/sqlite3" "--host=https://mapbox-node-binary.s3.amazonaws.com/" "--module_path=/Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/sqlite3/lib/binding/node-v14-darwin-x64" "--module=/Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node" "--remote_path=./sqlite3/v3.0.0/" "--package_name=node-v14-darwin-x64.tar.gz" "--staged_tarball=build/stage/sqlite3/v3.0.0/node-v14-darwin-x64.tar.gz" "--hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.0/" "--hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.0/node-v14-darwin-x64.tar.gz"
gyp ERR! cwd /Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/sqlite3
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=3.0.0 --major=3 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/sqlite3/lib/binding/node-v14-darwin-x64 --module=/Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node --remote_path=./sqlite3/v3.0.0/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/sqlite3/v3.0.0/node-v14-darwin-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.0/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.0/node-v14-darwin-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1008:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
node-pre-gyp ERR! System Darwin 14.1.0
node-pre-gyp ERR! command "node" "/Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.5.27
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=3.0.0 --major=3 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/sqlite3/lib/binding/node-v14-darwin-x64 --module=/Users/andrewbenner/Desktop/gitHub/login.webmaker.org/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node --remote_path=./sqlite3/v3.0.0/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/sqlite3/v3.0.0/node-v14-darwin-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.0/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.0/node-v14-darwin-x64.tar.gz' (1)
npm WARN deprecated lingo@0.0.5: This project is abandoned
npm WARN optional dep failed, continuing sqlite3@3.0.0
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andrewbenner/Desktop/gitHub/login.webmaker.org/npm-debug.log
```
