### ISSUE TITLE
NODE RUN will not select more than 2 items before crashing

### ISSUE THREAD

**Issue by dcforeman** [mozilla/webmaker-suite#45]
The install and setup script is a nightmare on windows 10, I had to install components one at a time, and now I can't recreate a run profile at all, the issue is with selection. If I put an x in more than once thing the software freaks out and crashes.

events.js:85
      listeners[i].call(self);
                  ^

TypeError: Cannot read property 'call' of undefined
    at emitNone (events.js:85:19)
    at Stream.emit (events.js:179:7)
    at Stream.Charm.end (C:\Users\danie\webmaker-suite\node_modules\charm\index.js:107:10)
    at Menu.close (C:\Users\danie\webmaker-suite\node_modules\terminal-menu\index.js:119:16)
    at Object.Menu.close (C:\Users\danie\webmaker-suite\node_modules\terminal-menu-program\menu.js:46:17)
    at Object.Menu.draw (C:\Users\danie\webmaker-suite\node_modules\terminal-menu-program\menu.js:139:10)
    at Object.Program.run (C:\Users\danie\webmaker-suite\node_modules\terminal-menu-program\program.js:40:19)
    at Object.Menu.handler (C:\Users\danie\webmaker-suite\node_modules\terminal-menu-program\menu.js:124:24)
    at emitTwo (events.js:100:13)
    at Menu.emit (events.js:185:7)

**Comment by Pomax** [comment]
I need to mark this repository as obsolete - this was a terminal installer for managing a whole bunch of code bases that have been shelved since. It is not recommended to try to make this work in any way on modern systems (and several of the installs will absolute break because the projects themselves aren't even in the locations the installer could find them 2 years ago)
